version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7029:80"
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Passwordhereyo1!
      ACCEPT_EULA: Y
      DATABASE_NAME: CrowdFunding
